Feature/94 sign up UI
jagaldol/chat-foodie pull request #112
Opened 2023-08-20 07:03 UTC by sm136599

## Summary

회원가입 창의 모든 기능을 구현하였습니다.

## Description

* 회원가입 시, 아이디, 비밀번호, 비밀번호 확인, 이메일에 대한 유효성 검사를 진행합니다. 
  * 아이디와 이메일에 대해선 서버와 통신하여 중복 검사를 추가로 진행합니다.
* 회원가입 버튼을 누르면 자동으로 이메일 인증창으로 넘어가고, 창이 렌더링되면서 회원가입 시 입력한 이메일로 인증코드가 전송됩니다.
* 이메일 인증을 하지 않은 채로 창을 닫게 되면, 자동으로 로그아웃이 됩니다.
  * 이메일 인증이 완료되지 않은 아이디로 로그인 시, 이메일 인증 창이 켜지게 되며 인증이 완료되어야 채팅 기능을 사용할 수 있습니다.

## Related Issue

Issue Number: close #94 
Fix: close #109

2023-08-20 07:38 UTC, jagaldol commented
![image](https://github.com/jagaldol/chat-foodie/assets/84557643/10179f9e-4605-4306-9985-e6598b55ca53)

엔터 치거나 회원가입 버튼 눌렀을 때 아이디에도 이메일의 에러메시지가 출력됩니다...!!

2023-08-20 07:41 UTC, jagaldol commented
![image](https://github.com/jagaldol/chat-foodie/assets/84557643/5f14ee79-c7a9-476f-a279-33e152d64be6)

인증 번호 전송 트리거 가 어떻게 되나요?

회원가입하고 나서 인증번호 입력칸을 클릭하니까 `인증 번호가 전송되었습니다.` 메시지가 출력되었는데 이상해서 테스트 해보다가 로그아웃 하고 새로 로그인할려고 로그인 창 키니까 인증 번호 전송되었다고 또 출력되네요 테스트 해주시길 바랍니다.

2023-08-20 08:15 UTC, jagaldol requested changes
수정 부탁드립니다

2023-08-20 08:15 UTC, jagaldol commented on client/src/containers/account/emailVerificationModal.tsx
> +          <div className="flex flex-col items-center">
혹시 인증 코드를 보낸 이메일에 대한 정보를 여기에다 표시 할 수 있나요?
개인정보 조회 api 써서 현재 이메일 정보만 랜더링 해주시면 될거 같은데

그리고 인증 메일 재전송 버튼도 만들어 주실래요?

2023-08-20 08:15 UTC, jagaldol commented on client/src/containers/account/emailVerificationModal.tsx
> +      .post("/email-verifications", undefined, { headers })
코멘트로도 남겼는데 이 모달에서는 재전송 버튼을 통해 보내게만 하고 회원가입 성공 시에 onClose하기 직전에 메일 보내는 api 호출 하는 식으로 하는 게 어떨까요.

2023-08-20 08:15 UTC, jagaldol commented on client/src/containers/account/emailVerificationModal.tsx
> +        alert("인증 번호가 전송되었습니다.")
코멘트에 적었다시피 alert를 사용하지 말고 modal내에 안내 메시지 칸을 만들어 state로 관리하면서 성공 실패했을 때 그곳을 세팅하는 식으로 수정부탁드릴께요.

회원가입 성공 시에 호출하는 api에는 성공 실패에 대한 별도의 핸들링하지 말고요

2023-08-20 08:15 UTC, jagaldol commented on client/src/containers/account/joinModal.tsx
> +            setErrors({ ...errors, loginId: "이미 존재하는 이메일 입니다." })
여기가 좀 이상한거 같은데 아까 테스트할때 잘될때도 있고 안될때도 있었거든요? 일단 수정하기 전에 충분히 다양하게 다시 테스트 진행해보고 버그 더 없게 면밀히 수정부탁드립니다

2023-08-20 08:15 UTC, jagaldol commented on server/src/main/java/net/chatfoodie/server/user/dto/UserRequest.java
> +                    .role(Role.ROLE_PENDING)
지금 이렇게 하셨는데 정상적으로 할려면 UserRepository.save(user) 했을때 반환 값으로 새롭게 만들어서 저장되는 User 객체가 반환 됩니다. 이걸로 하면 생일이나 룰이나 createdAt이나 기본값 전부 세팅되어있는 객체를 가지고 JWT를 만들 수 있으니까 서비스단에서 repository.save가 반환하는 User 객체로 JWT를 만들어 돌려주게 해주세요

2023-08-20 08:15 UTC, jagaldol commented on server/src/main/java/net/chatfoodie/server/user/service/UserService.java
> +        return JwtProvider.create(user);
여기에 create(user)대신에 save의 반환 값인 user를 넣어주세요!!

제가 웹소켓하면서 채팅방 만들때, 막 만들어진 채팅방 아이디를 api에서 리턴해주도록하면서 그렇게 짰는데 한번 확인해보시면 좋겠습니다!

2023-08-20 12:10 UTC, sm136599 commented on client/src/containers/account/emailVerificationModal.tsx
> +          <div className="flex flex-col items-center">
현재 api로 구현된 유저 정보 조회는 ROLE_USER만 가능하게 되어 있습니다.
권한 세팅을 다시하거나 이메일 정보만 조회하는 api를 만들거나 해야 할 것 같은데 어떤게 괜찮아 보이나요?

2023-08-20 12:10 UTC, sm136599 commented on client/src/containers/account/emailVerificationModal.tsx
> +        alert("인증 번호가 전송되었습니다.")
넵

2023-08-20 14:28 UTC, sm136599 commented on server/src/main/java/net/chatfoodie/server/user/service/UserService.java
> +        return JwtProvider.create(user);
baedb4b7a77f83a21dcc48eeafd9a6ca8c38679c 이 커밋 맞을 까요? 
적용했습니다.

2023-08-20 14:43 UTC, jagaldol commented on client/src/containers/account/emailVerificationModal.tsx
> +          <div className="flex flex-col items-center">
아! 유저 관련 api는 전부 자기 자신에만 적용하는 거라 PENDING 회원도 사용해도 되지 않을까요? 제 생각에는 권한을 PENDING까지 열어버리는게 좋을 거 같아요!

2023-08-20 14:44 UTC, jagaldol commented on server/src/main/java/net/chatfoodie/server/user/service/UserService.java
> +        return JwtProvider.create(user);
네 맞아요!

2023-08-20 15:09 UTC, sm136599 commented on client/src/containers/account/emailVerificationModal.tsx
> +          <div className="flex flex-col items-center">
그렇게 되면 이메일 인증화면에서 이메일 조회뿐 아니라 변경기능까지 만들 수 있겠내요!

2023-08-21 03:04 UTC, sm136599 commented on server/src/main/java/net/chatfoodie/server/user/service/UserService.java
> +        return JwtProvider.create(user);
return JwtProvider.create(userRepository.save(user)); 이런 식으로 로직을 변경하였는데(a6e2388b1baa890b09554128ef648fcc5ef44c63), jwt 토큰을 확인해보니 여전히 role이 null로 반환되었습니다. 
save 구현 코드를 보니 다음과 같았습니다.
```java
@Transactional
@Override
public <S extends T> S save(S entity) {

  Assert.notNull(entity, "Entity must not be null");
  
  if (entityInformation.isNew(entity)) {
    em.persist(entity);
    return entity;
  } else {
    return em.merge(entity);
  }
}
```
만약 새로 만들어진 entity면 리턴값으로 entity를 그대로 반환합니다.
따라서 처음 생성 시, role에 ROLE_PENDING 값을 넣어주는 것이 맞아보입니다.

2023-08-21 03:52 UTC, jagaldol commented on server/src/main/java/net/chatfoodie/server/user/service/UserService.java
> +        return JwtProvider.create(user);
제가 잘 몰랐네요... 알려주셔서 감사합니다

2023-08-21 09:24 UTC, jagaldol approved these changes
이상없어 보입니다. 수고 많으셨습니다.

2023-08-21 09:30 UTC, merged