유저 선호도 저장
jagaldol/chat-foodie pull request #64
Opened 2023-08-05 18:34 UTC by icarus012832

## Summary

food에서 구현하던 파트를 favor로 옮겼고, 각 user의 favor에 선호하는 음식 목록 저장. 저장 전에는 항상 favor 테이블을 삭제하고 id도 초기화 해줌.

## Description

favor 테이블에는 음식의 이름이 들어감.

## Related Issue

close #36

2023-08-06 06:17 UTC, sm136599 commented on server/src/main/java/net/chatfoodie/server/favor/controller/FavorController.java
> +    @PostMapping("/favor/saveUserFoodPreference")
API 문서 보시면 URL 주소가 /api/favors로 되어있습니다. 수정부탁드립니다.

2023-08-06 06:19 UTC, sm136599 commented on server/src/main/java/net/chatfoodie/server/favor/controller/FavorController.java
> +    public ResponseEntity<?> saveUserFoodPreference(@RequestBody FavorRequest.SaveUserFoodPreferenceDto requestDto) {
requestDto 파라미터에 @Valid annotation을 달아주시고, 에러를 잡을 수 있도록 Errors errors 파라미터도 추가해주세요.

2023-08-06 06:57 UTC, icarus012832 commented on server/src/main/java/net/chatfoodie/server/favor/controller/FavorController.java
> +    @PostMapping("/favor/saveUserFoodPreference")
수정 하였습니다.

2023-08-06 06:57 UTC, icarus012832 commented on server/src/main/java/net/chatfoodie/server/favor/controller/FavorController.java
> +    public ResponseEntity<?> saveUserFoodPreference(@RequestBody FavorRequest.SaveUserFoodPreferenceDto requestDto) {
수정하였습니다.

2023-08-06 07:03 UTC, sm136599 commented on server/src/main/java/net/chatfoodie/server/favor/controller/FavorController.java
> +    public ResponseEntity<?> saveUserFoodPreference(@RequestBody FavorRequest.SaveUserFoodPreferenceDto requestDto) {
또한, 이슈 #53 의 server/src/main/java/net/chatfoodie/server/user/controller/UserController.java 파일을 참고해서 요청을 보낸 자신의 선호도만 변경할 수 있게 해주세요.

2023-08-06 07:49 UTC, jagaldol requested changes

2023-08-06 07:49 UTC, jagaldol commented on server/src/main/java/net/chatfoodie/server/favor/controller/FavorController.java
> +    @PostMapping("/favors/saveUserFoodPreference")
주소 /favors로 바꿔주세요

2023-08-06 07:49 UTC, jagaldol commented on server/src/main/java/net/chatfoodie/server/favor/dto/FavorRequest.java
> +    public record SaveUserFoodPreferenceDto(Long userId, List<Long> favorIds) {
여기 favorIds를 foodIds로 바꿔주세요

2023-08-06 07:49 UTC, jagaldol commented on server/src/main/java/net/chatfoodie/server/favor/service/FavorService.java
> +        User user = userRepository.findById(userId).orElse(null);
orElseThrow(()-> new Exception404("해당 회원이 존재하지 않습니다"))로 바꿔주세요

2023-08-06 07:49 UTC, jagaldol commented on server/src/main/java/net/chatfoodie/server/favor/service/FavorService.java
> +        favorRepository.resetIdSequence();
Id Sequence를 초기화 해버리면 1부터 시작하는 걸로 아는데 1번 유저 말고도 2번 유저 3번 유저의 선호도가 같은 테이블 내에 존재하잖아요. 1번 유저가 선호도 설정하면서 초기화 해버리면 id 충돌 나지 않을 까요?

이부분은 문제가 될거 같아요

2023-08-06 07:49 UTC, jagaldol commented on server/src/main/java/net/chatfoodie/server/favor/service/FavorService.java
> +            Food food = foodRepository.findById(foodId).orElse(null);
여기도 orElseThrow로 404 에러를 줍시다.

2023-08-06 07:49 UTC, jagaldol commented on server/src/main/java/net/chatfoodie/server/favor/service/FavorService.java
> +            Food food = foodRepository.findById(foodId).orElse(null);
또한 foodRepository에 쿼리 하나씩 날리지 말고 findByIdIn으로 한번에 들고오세요

2023-08-06 07:49 UTC, jagaldol commented on server/src/main/java/net/chatfoodie/server/favor/service/FavorService.java
> +            if (food != null && user != null) {
앞에서 orElseThrow로 잡게 되면 필요 없어지는 if문

2023-08-06 07:49 UTC, jagaldol commented on server/src/main/java/net/chatfoodie/server/favor/dto/FavorRequest.java
> +        public List<Favor> toFavors() {
user나 food의 경우 service단에서 repository로 존재하는지 검사하면서 어차피 들고 온단말이죠 그걸 사용해서 Favor을 만드는게 정합성적인 측면에서 낫고 애초에 현재 이 메서드 안 쓰고 있는 거 같으니까 삭제 해주세요

2023-08-06 07:49 UTC, jagaldol commented on server/src/main/java/net/chatfoodie/server/favor/service/FavorService.java
> +                favorRepository.save(favor);
findByIdIn으로 한번에 들고오게 되면 stream map 써서 List<Favor> 만들고 그거는 saveAll 써가지고 한번에 저장할 수 있어요

2023-08-06 13:10 UTC, jagaldol commented
회원 전용 API로 변경하고 JWT 값을 바탕으로 해당회원의 정보를 업데이트하도록 하죠 API 문서 참고해주세요. requestDTO 수정해주세요

2023-08-07 08:10 UTC, sm136599 approved these changes
수고했어요

2023-08-07 08:19 UTC, jagaldol reviewed
이부분만 고쳐주세요

2023-08-07 08:19 UTC, jagaldol commented on server/src/main/java/net/chatfoodie/server/favor/controller/FavorController.java
> +                                                    @RequestBody @Valid FavorRequest.SaveUserFoodPreferenceDto requestDto, Errors error) {
Errors error 되있는데 다른 부분이랑 컨벤션 맞춰야해서 errors로 바꿀래요?

2023-08-07 08:19 UTC, jagaldol commented on server/src/main/java/net/chatfoodie/server/favor/service/FavorService.java
> +            }
여기 indent 맞춰주세요

2023-08-07 08:19 UTC, jagaldol commented on server/src/main/java/net/chatfoodie/server/favor/service/FavorService.java
> +                        .created_at(LocalDateTime.now())
now로 보내도 되는데 mysql에서 now()로 default 저장되있어서 없어도 되요

2023-08-07 08:27 UTC, jagaldol approved these changes

2023-08-07 08:28 UTC, merged